apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-exposed-deployment
  labels:
    app: nginx-exposed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exposed
  template:
    metadata:
      labels:
        app: nginx-exposed
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exposed-service
spec:
  selector:
    app: nginx-exposed
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
